[FEA] Use the GitHub `.zip` URI instead of `GIT_REPOSITORY` and `GIT_BRANCH`
rapidsai/rapids-cmake pull request #257
Opened 2022-08-30 06:55 UTC by trxcllnt

This PR uses the GitHub `.zip` URI instead of `GIT_REPOSITORY` and `GIT_BRANCH` so `rapids-cmake` can be loaded on machines that don't have git installed.

2022-08-30 14:09 UTC, robertmaynard commented
With the update to the latest version of CPM it handles setting `CMP0135` so we only need to manually specify it when downloading the nvcomp binaries.

Given the switch to a zip in RAPIDS.cmake we should also enable `CMP0135` when executing the download.

2022-08-30 14:11 UTC, robertmaynard requested changes

2022-08-30 14:11 UTC, robertmaynard commented on RAPIDS.cmake
>  include(FetchContent)
```suggestion
if(POLICY CMP0135)
  cmake_policy(PUSH)
  cmake_policy(SET CMP0135 NEW)
endif()
include(FetchContent)
```

2022-08-30 14:11 UTC, robertmaynard commented on RAPIDS.cmake
>  FetchContent_GetProperties(rapids-cmake)
```suggestion
if(POLICY CMP0135)
  cmake_policy(POP)
endif()
FetchContent_GetProperties(rapids-cmake)
```

2022-08-30 18:48 UTC, trxcllnt commented on RAPIDS.cmake
> +  URL https://github.com/rapidsai/rapids-cmake/archive/refs/heads/branch-22.10.zip
Oh yeah thanks, didn't realize I hard-coded this!

2022-08-30 19:05 UTC, robertmaynard approved these changes

2022-08-30 19:06 UTC, robertmaynard commented
rerun tests

2022-08-30 19:10 UTC, bdice approved these changes

2022-09-01 20:15 UTC, bdice approved these changes

2022-09-01 20:15 UTC, bdice commented on RAPIDS.cmake
> +# Allow users to control which Github repo is fetched
```suggestion
# Allow users to control which GitHub repo is fetched
```

2022-09-01 20:23 UTC, robertmaynard approved these changes

2022-09-08 00:14 UTC, vyasr commented
@robertmaynard @trxcllnt is this PR waiting on anything or can it be merged?

2022-09-09 20:55 UTC, trxcllnt commented
@gpucibot merge

2022-09-09 20:55 UTC, merged