Add support for cloning Google benchmark
rapidsai/rapids-cmake pull request #293
Opened 2022-10-14 18:11 UTC by vyasr

## Description

Many RAPIDS libraries use Google benchmark to manage C++ benchmarks. This PR centralizes the dependency and the version management.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/rapids-cmake/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.
- [x] The `cmake-format.json` is up to date with these changes.
- [x] I have added new files under rapids-cmake/
   - [x] I have added include guards (`include_guard(GLOBAL)`)
   - [x] I have added the associated docs/ rst file and update the api.rst

2022-10-14 18:17 UTC, vyasr commented
I should add that cuML and cuGraph's current versions of this function [specify the lib dir for gbench](https://github.com/rapidsai/cuml/blob/branch-22.12/cpp/cmake/thirdparty/get_gbench.cmake#L33), but I don't think we need or want that. Please correct me if I'm wrong.

2022-10-14 19:36 UTC, robertmaynard requested changes
Looks great. Just a couple of small changes needed

2022-10-14 19:36 UTC, robertmaynard commented on rapids-cmake/cpm/gbench.cmake
> +.. versionadded:: v21.12.00
```suggestion
.. versionadded:: v22.12.00
```

2022-10-14 19:36 UTC, robertmaynard commented on rapids-cmake/cpm/gbench.cmake
> +  benchmark::benchmark targets will be created
Looks like `gbench` also has a benchmark::benchmark_main target so lets expose that as well.

2022-10-14 19:40 UTC, robertmaynard commented
> I should add that cuML and cuGraph's current versions of this function [specify the lib dir for gbench](https://github.com/rapidsai/cuml/blob/branch-22.12/cpp/cmake/thirdparty/get_gbench.cmake#L33), but I don't think we need or want that. Please correct me if I'm wrong.

We will want to specify the install directory if `INSTALL_EXPORT_SET` is set. But we will want to use `rapids_cmake_install_lib_dir` to compute the correct location. I expect this was done so it doesn't go into something like `lib64` and therefore breaks conda layout requirements.

2022-10-14 20:13 UTC, bdice approved these changes
No comments aside from what @robertmaynard mentioned. Nice, thanks for doing this!

2022-10-14 21:55 UTC, vyasr commented
> > I should add that cuML and cuGraph's current versions of this function [specify the lib dir for gbench](https://github.com/rapidsai/cuml/blob/branch-22.12/cpp/cmake/thirdparty/get_gbench.cmake#L33), but I don't think we need or want that. Please correct me if I'm wrong.
> 
> We will want to specify the install directory if `INSTALL_EXPORT_SET` is set. But we will want to use `rapids_cmake_install_lib_dir` to compute the correct location. I expect this was done so it doesn't go into something like `lib64` and therefore breaks conda layout requirements.

I'm now setting the `CMAKE_INSTALL_LIBDIR` for this target unconditionally (using `rapids_cmake_install_lib_dir`). I'm assuming that the `BENCHMARK_ENABLE_INSTALL` option for GBench will take care of whether installation happens at all so it should be safe to always set this.

2022-10-21 17:17 UTC, vyasr commented
@robertmaynard are you happy with the current state of this PR?

2022-10-21 17:31 UTC, robertmaynard approved these changes
LGTM, thank you

2022-10-21 17:39 UTC, vyasr commented
@gpucibot merge

2022-10-21 17:39 UTC, merged