Reduce error handling verbosity in CI tests scripts
rapidsai/rapids-cmake pull request #370
Opened 2023-02-10 18:56 UTC by AjayThorve

This PR adds a less verbose [trap method](https://github.com/rapidsai/cugraph/blob/f2b081075704aabc789603e14ce552eac3fbe692/ci/test.sh#L19), for error handling to help ensure that we capture all potential error codes in our test scripts, and works as follows:

- setting an environment variable, EXITCODE, with a default value of 0
- setting a trap statement triggered by ERR signals which will set EXITCODE=1 when any commands return a non-zero exit code

cc @ajschmidt8

2023-02-10 20:56 UTC, ajschmidt8 requested changes

2023-02-10 20:56 UTC, ajschmidt8 commented on ci/test_cpp.sh
>  ctest --schedule-random --output-on-failure
```suggestion
rapids-logger "Begin cpp tests"
cmake -S testing -B build

cd build

EXITCODE=0
trap "EXITCODE=1" ERR
set +e
ctest --schedule-random --output-on-failure
```

I think we should move this to just above the `ctest` invocation.

The other parts should fail immediately if there's an error.

2023-02-10 21:00 UTC, robertmaynard reviewed
I am confused.

The PR title is `Reduce error handling verbosity in CI tests scripts` but the scripts are now longer. What verbosity is this intending to reduce?

2023-02-10 21:10 UTC, ajschmidt8 commented
> I am confused.
> 
> The PR title is `Reduce error handling verbosity in CI tests scripts` but the scripts are now longer. What verbosity is this intending to reduce?

Good point. This change doesn't have much effect on `rapids-cmake` since it's test scripts are pretty succinct.

In other repositories, these changes were meant to replace the many conditional code blocks that existed previously for capturing error codes (like [this file](https://github.com/rapidsai/cudf/pull/12738/files#diff-12c1ee18bba80b27398d5173148eaba86ea281dea120e3f055989287cbd7763c) for cudf).

@robertmaynard, if you want us to close this PR since `rapids-cmake` has a small test script that's fine. I initially just created a list of all the GHAs repositories that should be checked which is why this PR was opened.

2023-02-10 21:10 UTC, AjayThorve commented
> I am confused.
> 
> The PR title is `Reduce error handling verbosity in CI tests scripts` but the scripts are now longer. What verbosity is this intending to reduce?

Hey @robertmaynard, you are right. This PR was part of a larger effort across all repos, and the title applied to all the repos except rapids-cmake. Infact in this case, as you mentioned it's adding more lines. Apologies for the confusion, but the aim of the change is to use the `trap` method to catch ERR, and while in most repositories across rapidsai, it significantly reduced the verbosity, in the case of rapids-cmake, we can may be use `trap` to keep error handling consistent across projects?

2023-02-10 22:21 UTC, robertmaynard commented
Absolutely fine moving over to using trap. Let's just update the pr title

2023-02-13 16:49 UTC, bdice commented on ci/test_cpp.sh
> +set +e
Add newline before calling `ctest`.
```suggestion
set +e

```

2023-02-13 16:50 UTC, bdice approved these changes

2023-02-13 22:51 UTC, ajschmidt8 approved these changes

2023-02-13 22:52 UTC, ajschmidt8 commented
/merge

2023-02-13 22:52 UTC, merged