Add rapids_cpm_cccl feature.
rapidsai/rapids-cmake pull request #495
Opened 2023-12-01 22:05 UTC by bdice

## Description
This PR adds a new function `rapids_cpm_cccl` that adds CCCL from the new monorepo. This will eventually replace `rapids_cpm_thrust` and `rapids_cpm_libcudacxx`.

**This PR is an early draft that I'm opening to ask for help.**

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/rapids-cmake/blob/HEAD/CONTRIBUTING.md).
- [ ] New or existing tests cover these changes.
- [ ] The documentation is up to date with these changes.
- [ ] The `cmake-format.json` is up to date with these changes.
- [ ] I have added new files under rapids-cmake/
   - [ ] I have added include guards (`include_guard(GLOBAL)`)
   - [ ] I have added the associated docs/ rst file and update the api.rst

2023-12-05 15:03 UTC, robertmaynard requested changes

2023-12-05 16:38 UTC, bdice commented on rapids-cmake/cpm/cccl.cmake
> +function(rapids_cpm_cccl NAMESPACE namespaces_name)
I expected that we need to support a custom namespace argument that we propagate to Thrust / CUB somehow? Was the need for custom namespaces changed between 1.17.2 and 2.2.0? It looks like that custom namespace code is still around in Thrust/CUB.

https://github.com/NVIDIA/cccl/blob/v2.2.0/thrust/thrust/detail/config/namespace.h#L31

2023-12-05 16:47 UTC, robertmaynard commented on rapids-cmake/cpm/cccl.cmake
> +function(rapids_cpm_cccl NAMESPACE namespaces_name)
The custom namespace that Thrust uses now is `CCCL`

2023-12-05 16:50 UTC, bdice commented on rapids-cmake/cpm/cccl.cmake
> +    include("${rapids-cmake-dir}/export/find_package_root.cmake")
I tried a few ways of updating this with the comments above/below but I can't figure out how to make the tests pass after changing this. Can you help me refactor this?

2023-12-05 16:57 UTC, bdice commented on rapids-cmake/cpm/cccl.cmake
> +function(rapids_cpm_cccl NAMESPACE namespaces_name)
Okay. I gave this a shot. See if c8232bb45ee6fc25441d7a2c41545f1661fe5212 is what you expect.

2023-12-05 17:40 UTC, bdice commented on rapids-cmake/cpm/cccl.cmake
> +function(rapids_cpm_cccl NAMESPACE namespaces_name)
How does removing the custom namespace affect cudf, which needs to have its own patched CCCL?

2023-12-05 17:51 UTC, robertmaynard commented on rapids-cmake/cpm/cccl.cmake
> +function(rapids_cpm_cccl NAMESPACE namespaces_name)
It won't have an impact. Even currently we can only have a single version of Thrust or CCCL brought into a CMake project. The custom CMake namespace controls that thrust offered was due to an internal design choice that didn't need to be exposed to users/projects. Looking back on it rapids-cmake should have always just created something like a ` RAPIDS::Thrust` target

2023-12-06 15:01 UTC, robertmaynard commented on rapids-cmake/cpm/cccl.cmake
> +    include("${rapids-cmake-dir}/export/find_package_root.cmake")
Sure, I will at this today

2023-12-06 16:22 UTC, robertmaynard commented on rapids-cmake/cpm/cccl.cmake
> +    include("${rapids-cmake-dir}/export/find_package_root.cmake")
Looks to be a bug in Thrust/CCCL cmake logc that doesn't properly setup the targets on the first pass. Tracking down exactly what is wrong.

2023-12-06 16:55 UTC, robertmaynard commented on rapids-cmake/cpm/cccl.cmake
> +    include("${rapids-cmake-dir}/export/find_package_root.cmake")
https://github.com/NVIDIA/cccl/pull/1182

We can work around this for CMake 3.24+ users. For people on 3.23 the `CCCL::CCCL` target still works and will bring in thrust stuff as needed. I expect that most projects should migrate to `CCCL::CCCL` so this issue is minor and only exposed due to how our tests always verify all targets

2023-12-06 17:01 UTC, robertmaynard commented on rapids-cmake/cpm/cccl.cmake
> +    include("${rapids-cmake-dir}/export/find_package_root.cmake")
Pushed an update to this PR that works around the `CCCL::Thrust` issue, and removed unneeded logic from `cpm/cccl.cmake`.

2023-12-07 14:53 UTC, bdice commented on rapids-cmake/cpm/versions.json
> +      "git_tag" : "cccl-2.2.0"
Reverting cuCollections changes so we can merge this.
```suggestion
      "git_url" : "https://github.com/NVIDIA/cuCollections.git",
      "git_tag" : "7c76a124df0c2cd3fd66e3e080b9470a3b4707c6"
```

2023-12-07 17:41 UTC, bdice commented
/merge

2023-12-07 17:41 UTC, merged