Remove rapids_cuda_patch_toolkit
rapidsai/rapids-cmake pull request #661
Opened 2024-07-29 19:03 UTC by bdice

## Description
This PR removes the deprecated feature `rapids_cuda_patch_toolkit`.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/rapids-cmake/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.
- [x] The `cmake-format.json` is up to date with these changes.
- [ ] I have added new files under rapids-cmake/
   - [ ] I have added include guards (`include_guard(GLOBAL)`)
   - [ ] I have added the associated docs/ rst file and update the api.rst

2024-07-29 19:04 UTC, KyleFromNVIDIA approved these changes

2024-07-29 19:56 UTC, robertmaynard approved these changes

2024-07-29 19:57 UTC, robertmaynard requested changes
Just have a 'few' tests to remove, and a couple that need to refactored to use `cccl`

2024-08-02 15:17 UTC, robertmaynard commented
Closing as https://github.com/rapidsai/rapids-cmake/pull/665 replaces this

2024-08-02 15:17 UTC, closed without merging