Disallow nvcomp git checkout
rapidsai/rapids-cmake pull request #704
Opened 2024-10-16 13:48 UTC by bdice

## Description
Closes #702.

This adopts a minimal approach that does not affect parsing logic, it only disables git checkout of the nvcomp dependency.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/rapids-cmake/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.
- [x] The `cmake-format.json` is up to date with these changes.
- [ ] I have added new files under rapids-cmake/
   - [ ] I have added include guards (`include_guard(GLOBAL)`)
   - [ ] I have added the associated docs/ rst file and update the api.rst

2024-10-16 13:49 UTC, bdice commented
I am marking this as non-breaking because the nvcomp 2.2.0 git checkout has been unsupported for a while.

2024-10-16 16:35 UTC, KyleFromNVIDIA requested changes
You'll need to update the tests in CI to account for the fact that Git is no longer supported.

You may even consider throwing an error if `PROPRIETARY_BINARY` is not passed.

2025-01-21 15:02 UTC, robertmaynard commented
@bdice Are you planning on working on this for 25.02? Otherwise we can close it and re-open when work resumes

2025-04-22 22:10 UTC, bdice commented
Closing for now. I haven't had bandwidth to pick this up.

2025-04-22 22:10 UTC, closed without merging